set -a terminal-features "tmux-256color:RGB"
set -g extended-keys on
set -g prefix C-SPACE
set -g base-index 1
set -g renumber-windows on   
set -g mode-keys vi
set -g status-position top
set -g status-justify absolute-centre
set -g status-style "bg=default"
set -g window-status-current-style "fg=black bg=white  "
set -g window-status-current-style "fg=colour255,bg=default,bold"
set -g window-status-separator ""
set -g window-status-format "#[fg=colour240]#[default] #I:#W#{?window_flags,#{window_flags},} #[fg=colour240]#[default]"
set -g window-status-current-format "#[fg=colour252]#[default] #I:#W#{?window_flags,#{window_flags},} #[fg=colour252]#[default]"
set -g status-interval 5
set -g status-left "#S"
set -g status-right ""
# for debugging
set -g remain-on-exit "off"

bind r source-file "~/.config/tmux/tmux.conf"
bind b set -g status
bind x kill-window
bind-key -n M-BSpace send-keys C-w
bind G neww -n "git" -S lazygit
bind E show-environment -g
